Added localization - react-native-localization library
Mykhailo-Kaduk/Red-shirt pull request #1
Opened 2020-10-07 18:57 UTC by stoyar

2020-10-08 09:18 UTC, andriibodryi requested changes

2020-10-08 09:18 UTC, andriibodryi commented on src/localization/Localization.ts
> +});
лучше создать отдельный файл для каждого языка и здесь их уже подтягивать
просто может быть такое, что приложение серьезно будет разрастаться, количество языков увеличиваться и файл будет иметь 1к+ строк

2020-10-08 16:13 UTC, stoyar commented on src/localization/Localization.ts
> +});
Да, есть смысл)

2020-10-09 05:46 UTC, andriibodryi approved these changes

2020-10-09 09:00 UTC, Mykhailo-Kaduk approved these changes

2020-10-09 11:47 UTC, merged