[Feature/prise er tab]: Added PriceError tab layouts
Mykhailo-Kaduk/Red-shirt pull request #15
Opened 2020-10-28 15:52 UTC by stoyar

2020-10-28 16:02 UTC, Mykhailo-Kaduk commented on src/screens/PriceError/PriceError.tsx
> +          <Ticket key={index.toString()} {...item} />
please do not use index as a key

2020-10-29 08:54 UTC, andriibodryi requested changes

2020-10-29 08:54 UTC, andriibodryi commented on src/screens/PriceError/PriceError.tsx
> +  }, []);
const newState = prevState;
you copied the url of the state array, mutated and returned the mutated state, although a new one needs to be returned. As option you may write like const newState =[...prevState];
or more simple just return [... prevState, { department, total }]

2020-10-29 08:54 UTC, andriibodryi commented on src/screens/PriceError/PriceError.tsx
> +        {corrections.map((item, index) => (
instead of map please use FlatList for any lists

2020-10-29 08:54 UTC, andriibodryi commented on src/screens/PriceError/PriceError.tsx
> +        {corrections.length > 0 && (
I think better to use !!array.length && (...) or Boolean(array.length) && (...) instead of array.length > 0 && (...)

2020-10-29 08:54 UTC, andriibodryi commented on src/screens/PriceError/elements/AddDepartmentModal/styles.ts
> +  },
you may use 'small' prop for Button instead

2020-10-29 08:54 UTC, andriibodryi commented on src/screens/PriceError/PriceError.tsx
> +      <ScrollView style={styles.scrollContainer}>
ScreenView has 'scrolled' prop for ScrollView

2020-10-29 12:07 UTC, Mykhailo-Kaduk approved these changes

2020-10-29 12:15 UTC, andriibodryi approved these changes

2020-10-29 12:25 UTC, merged