[Feature/fetch departments flow]: Fixed departments list, departments data model
Mykhailo-Kaduk/Red-shirt pull request #17
Opened 2020-11-02 20:59 UTC by stoyar

2020-11-04 06:14 UTC, andriibodryi requested changes

2020-11-04 06:14 UTC, andriibodryi commented on src/api/departments/sendCorrections.ts
> +    console.log(corrections);
please, remove log

2020-11-04 06:14 UTC, andriibodryi commented on src/screens/PriceError/elements/RequestStatusModal/RequestStatusModal.tsx
> +        ) : (
may you combine this two elements into one isLoading?

2020-11-04 07:59 UTC, stoyar commented on src/api/departments/sendCorrections.ts
> +    console.log(corrections);
This is temporary, because of ESLint Error for unused props

2020-11-04 11:31 UTC, andriibodryi approved these changes

2020-11-04 16:01 UTC, Mykhailo-Kaduk commented on src/screens/PriceError/elements/RequestStatusModal/RequestStatusModal.tsx
> +        {isLoading || (
please move this piece of code into condition below

2020-11-04 16:52 UTC, Mykhailo-Kaduk commented on src/screens/PriceError/PriceError.tsx
> +    setShowRequestStatus(true);
Maybe you should use the value from store instead of setting it from inside the component

2020-11-04 20:06 UTC, stoyar commented on src/screens/PriceError/PriceError.tsx
> +    setShowRequestStatus(true);
This is not the isLoading value. I use this state for show/hide modal with request status and controls. isLoading don't fit for this purpose

2020-11-05 09:28 UTC, Mykhailo-Kaduk approved these changes

2020-11-05 09:28 UTC, Mykhailo-Kaduk commented on src/screens/PriceError/elements/AddDepartmentModal/AddDepartmentModal.tsx
> +        <TouchableOpacity onPress={() => setDepartment(item.id)} style={style}>
please make this callback memoized)

2020-11-05 10:04 UTC, merged