SM-63 add return-goods flow
Mykhailo-Kaduk/Red-shirt pull request #42
Opened 2020-11-24 07:29 UTC by Mykhailo-Kaduk

2020-11-24 10:09 UTC, andriibodryi requested changes

2020-11-24 10:09 UTC, andriibodryi commented on src/screens/Product/Product.tsx
> +      reasons?.find(({ id }: { id: string }) => id === reason)?.title || null,
I think better to return '' instead of null, because if you will use null, I must, for example, for using **selectedReason**  everywhere I need  to add ? operator for string methods

Or make it more expected and please rename this variable like **selectedReasonOrNull**

2020-11-24 10:09 UTC, andriibodryi commented on src/screens/Product/Product.tsx
> +      reasons?.find(({ id }: { id: string }) => id === reason)?.title || null,
https://www.youtube.com/watch?v=QwycPnpp6uQ

2020-11-24 11:12 UTC, artur-h commented on src/screens/PLU/PLU.tsx
> +  // } = useRoute();
I guess this shouldn't be here

2020-11-25 07:55 UTC, artur-h commented on src/store/returns/selectors.ts
> +  }, 0);
Is not a shorthanded version just better here?
Like this: `goods.reduce((acc, { price }) => acc + price, 0);`

2020-11-25 07:56 UTC, artur-h commented on src/store/returns/selectors.ts
> +  }, 0);
Same here

2020-11-25 10:50 UTC, artur-h approved these changes

2020-11-25 11:27 UTC, merged