Feature/basic ui components
Mykhailo-Kaduk/Red-shirt pull request #6
Opened 2020-10-12 15:00 UTC by andriibodryi

2020-10-13 09:34 UTC, Mykhailo-Kaduk commented on src/components/Button/Button.tsx
> +/* eslint-disable react/jsx-props-no-spreading */
Think we should add it to config

2020-10-13 09:34 UTC, Mykhailo-Kaduk commented on src/components/Button/Button.tsx
> +    Boolean(isLoading),
!!isLoading

2020-10-13 09:34 UTC, Mykhailo-Kaduk commented on src/components/Input/useAnimation.ts
> +import { Animated } from 'react-native';
please move this file to Input/hooks/useAnimation.ts

2020-10-13 09:34 UTC, Mykhailo-Kaduk commented on src/hooks/useComponentDidUpdate.ts
> +  const [didMount, setDidMount] = useState(false);
replace this with useRef, usestate call will trigger rerender

2020-10-13 13:38 UTC, Mykhailo-Kaduk approved these changes

2020-10-15 08:38 UTC, stoyar requested changes

2020-10-15 10:05 UTC, stoyar commented on src/screens/User/User.tsx
> +        <>
We need consider how to use React.Fragment component - either shorten or full form

2020-10-15 10:05 UTC, stoyar commented on tsconfig.json
> +      ]
Why did you remove trailing commas?

2020-10-15 12:44 UTC, andriibodryi commented on tsconfig.json
> +      ]
because json will get the error if after last item we pass the comma

2020-10-15 12:46 UTC, andriibodryi commented on src/components/ScreenView/ScreenView.tsx
> +    <SafeAreaView style={styles.safeAreaView}>
Will be removed before release. As I sad before, I develop using IOS emulator

2020-10-15 13:35 UTC, stoyar approved these changes

2020-10-15 15:48 UTC, merged