105-106/bugfix/price-formatting
Mykhailo-Kaduk/Red-shirt pull request #63
Opened 2020-12-10 12:12 UTC by artur-h

2020-12-10 12:59 UTC, andriibodryi requested changes

2020-12-10 12:59 UTC, andriibodryi commented on src/screens/Product/components/ChangePriceModal/ChangePriceModal.tsx
> +    setPrice(toFixed(productPrice, 2));
Unneeded useEffect and rerender
you may pass toFixed(productPrice, 2) as initial value like 
`const [price, setPrice] = useState( toFixed(productPrice, 2));`

2020-12-10 12:59 UTC, andriibodryi commented on src/components/Price/Price.tsx
> +      {currency + toFixed(value, 2)}
please, pass this calculation into useMemo

2020-12-10 12:59 UTC, andriibodryi commented on src/utils/formatPrice.ts
> +  if (value.indexOf(decimalMark) >= 0) {
please, use includes instead of indexOf

2020-12-11 06:04 UTC, andriibodryi approved these changes

2020-12-11 08:55 UTC, Mykhailo-Kaduk approved these changes

2020-12-11 09:08 UTC, merged