SM-148/feature/implement flow for sending returns data
Mykhailo-Kaduk/Red-shirt pull request #90
Opened 2020-12-29 13:57 UTC by artur-h

2020-12-29 14:21 UTC, andriibodryi requested changes

2020-12-29 14:21 UTC, andriibodryi commented on src/store/returns/utils/transformEmptiesForAPI.ts
> +};
you may use reduce instead of forEach

2020-12-29 14:21 UTC, andriibodryi commented on src/store/returns/utils/transformEmptiesForAPI.ts
> +    const outcomeReturns: OutcomeReturns = {
you may move **outcomeReturns** from loop

2020-12-29 14:21 UTC, andriibodryi commented on src/store/customer/sagas/fetchCustomerSaga.ts
> +        }),
extra operation. **loyaltyCardNumber** already passed in api call fetchCustomer.ts, line 17

2020-12-29 15:47 UTC, artur-h commented on src/store/customer/sagas/fetchCustomerSaga.ts
> +        }),
yes, thank you!

2020-12-30 07:51 UTC, andriibodryi approved these changes

2020-12-30 14:02 UTC, Mykhailo-Kaduk approved these changes

2020-12-30 14:11 UTC, merged